### PR TITLE
Upgrade to support Rustler 0.22

### PR DESCRIPTION
**Pull request by bromanko**
I'm attempting to extend rustled_syntect to support loading additional SyntaxSets. I've never written any Rust before, though. I figured it would be a small start to upgrade to using the latest version of Rustler. This introduced a new set of Rust macros for building your Nif. I'd love any feedback on this.

### CODE REVIEW

**Comment by valpackett** [comment]
Nice, thanks!

Why does macOS require these linker flags? Would it also require them on `aarch64-apple-darwin`?

**Comment by bromanko** [comment]
I was responding to a [new warning](https://github.com/rusterlium/rustler/blob/66616dbcf136026c1442d38d321866e0f404deff/rustler_mix/lib/rustler/compiler.ex#L93) when compiling on macOS. 

I did not experience the issue despite being on x86_64-apple-darwin. I assume this is because my environment is configured via Nix and not using the standard MacOS toolchain.

You had a good question. I found [this issue](https://github.com/rusterlium/rustler/issues/403#issuecomment-965964486) which ammends the config to work on both architectures. I’ll switch it.

**Comment by valpackett** [comment]
Oh, okay. Yes, the `cfg` version looks better.

> I did not experience the issue despite being on x86_64-apple-darwin

Probably because rustler (the exact place you linked to) actually currently provides the args by itself, and the warning is that rustler 1.0.0 will stop doing that.

**Comment by bromanko** [comment]
Updated the config.

**Comment by valpackett** [comment]
Thanks!

**Pull request merged**
